### ISSUE TITLE
The script didn't run on Debian (12)

### ISSUE THREAD

**Issue by giteration-maker** [captainzero93/security_harden_linux#1]
When I ran with Debian 12.0, I faced an error: "This script requires Ubuntu 18.04 or later."
  
<p>I changed the script to make it run with Debian also:
<code>
  if [[ "$os_name" == "Ubuntu" && $(echo "$os_version < 18.04" | bc) -eq 1 ]]; then
        handle_error "This script requires Ubuntu 18.04 or later. Detected version: $os_version"
	elif [[ "$os_name" == "Debian" && $(echo "$os_version < 12.0" | bc) -eq 1 ]]; then
	handle_error "This script requires Debian 12.0 or later. Detected version: $os_version"
    fi</code>
</p>

**Comment by captainzero93** [comment]
Thanks, I had not tested it on Debian yet ! 
Did anything break ? Debian version?

**Comment by giteration-maker** [comment]
> Thanks, I had not tested it on Debian yet ! Did anything break ? Debian version?

I didn't find any issues.

**Comment by captainzero93** [comment]
updated, thanks for testing
